---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeovirt
  namespace: konveyor-forklift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakeovirt
  template:
    metadata:
      labels:
        app: fakeovirt
    spec:
      containers:
      - name: fakeovirt
        image: localhost:5001/fakeovirt:latest
        ports:
        - containerPort: 12346
        env:
          - name: NAMESPACE
            value: konveyor-forklift
          - name: PORT
            value: "12346"
---
apiVersion: v1
kind: Service
metadata:
  name: fakeovirt
  namespace: konveyor-forklift
spec:
  selector:
    app: fakeovirt
  type: ClusterIP
  ports:
  - name: fakeovirt
    port: 12346
    targetPort: 12346